spring.application.name=demoProject

# replace with yours
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_p-yKek-TSZjl-HxxEMF@mysql-sanjai-sanjai6369kumar-477c.k.aivencloud.com:27144/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_p-yKek-TSZjl-HxxEMF


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081