spring.application.name=demoProject

spring.datasource.url=jdbc:mysql://mysql-38746e39-naveensanmugam2005-2105.a.aivencloud.com:27552/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=YOUR_NEW_PASSWORD_HERE

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
