spring.application.name=demoProject
#spring.datasource.url=jdbc:mysql://avnadmin:AVNS_p-yKek-TSZjl-HxxEMF@mysql-sanjai-sanjai6369kumar-477c.k.aivencloud.com:27144/defaultdb?ssl-mode=REQUIRED
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_p-yKek-TSZjl-HxxEMF

spring.datasource.url=jdbc:mysql://mysql-38746e39-naveensanmugam2005-2105.a.aivencloud.com:27552/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_gVcs8hnqf_lNa76VcCF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081